"""drop_legacy_metrics_tables

Revision ID: c8f35ab49079
Revises: 2b3c4d5e6f7g
Create Date: 2026-02-12 09:58:20.202207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8f35ab49079'
down_revision = '2b3c4d5e6f7g'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_id', table_name='metrics')
    op.drop_index('ix_metrics_resource_id', table_name='metrics')
    op.drop_index('ix_metrics_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_process_metrics_id', table_name='process_metrics')
    op.drop_index('ix_process_metrics_resource_id', table_name='process_metrics')
    op.drop_index('ix_process_metrics_timestamp', table_name='process_metrics')
    op.drop_table('process_metrics')
    op.alter_column('alerts', 'rule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'rule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('process_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('process_pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpu_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='process_metrics_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='process_metrics_pkey')
    )
    op.create_index('ix_process_metrics_timestamp', 'process_metrics', ['timestamp'], unique=False)
    op.create_index('ix_process_metrics_resource_id', 'process_metrics', ['resource_id'], unique=False)
    op.create_index('ix_process_metrics_id', 'process_metrics', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('memory_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('disk_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('network_in', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('network_out', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='metrics_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='metrics_pkey')
    )
    op.create_index('ix_metrics_timestamp', 'metrics', ['timestamp'], unique=False)
    op.create_index('ix_metrics_resource_id', 'metrics', ['resource_id'], unique=False)
    op.create_index('ix_metrics_id', 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###
